"""Models package - exports all Pydantic models."""

from .user import UserBase, UserCreate, UserLogin, UserOut, Role
from .auth import TokenResponse
from .assessment import (
    AssessmentBase,
    AssessmentCreate,
    AssessmentUpdate,
    AssessmentOut,
    MarkUpload,
    MarksUploadRequest,
    MarksUploadResponse,
    SampleGenerateRequest,
    SampleGenerateResponse,
    ModerationSubmitRequest,
    ModerationDecisionRequest,
    ThirdMarkerDecisionRequest,
    SampleItemOut,
    ModerationCaseOut,
    LecturerDashboardStats,
    ModeratorDashboardStats,
    ThirdMarkerDashboardStats,
    AdminStats,
    AuditEventOut,
    AssessmentStatus,
    ModerationDecision,
    ThirdMarkerDecision,
    SampleMethod,
    ModerationFormResponse,
    ModerationFormSubmit,
    ModerationFormOut,
)

__all__ = [
    # User models
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserOut",
    "Role",
    "TokenResponse",
    # Assessment models
    "AssessmentBase",
    "AssessmentCreate",
    "AssessmentUpdate",
    "AssessmentOut",
    "MarkUpload",
    "MarksUploadRequest",
    "MarksUploadResponse",
    "SampleGenerateRequest",
    "SampleGenerateResponse",
    "ModerationSubmitRequest",
    "ModerationDecisionRequest",
    "ThirdMarkerDecisionRequest",
    "SampleItemOut",
    "ModerationCaseOut",
    "LecturerDashboardStats",
    "ModeratorDashboardStats",
    "ThirdMarkerDashboardStats",
    "AdminStats",
    "AuditEventOut",
    # Moderation form models
    "ModerationFormResponse",
    "ModerationFormSubmit",
    "ModerationFormOut",
    # Types
    "AssessmentStatus",
    "ModerationDecision",
    "ThirdMarkerDecision",
    "SampleMethod",
]
